server.port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root1
    password: root1
  jpa:
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
